import type { Metadata } from "next";
import localFont from "next/font/local";
import "../globals.css";
import ToastProvider from "../../context/ToastProvider";
import MainNavigation from "../app-components/Navigation";
import SideNavBar from "@/components/common/SideNavBar";
import { fetchNotificationCount } from "@/libs/actions/notification.action";
import ThemeProvider from "@/context/ThemeProvider";

const barlow = localFont({ src: "../../public/fonts/Barlow-Regular.ttf" });

export const metadata: Metadata = {
  title: "Nomeo Blog 1.0",
  description: "Generated by create next app",
};

export default async function RootLayout({children}: Readonly<{ children: React.ReactNode }>) {
  const notifications = await fetchNotificationCount();
  const counts = notifications && notifications.counts;

  return (
    <html lang="en">
      <body className={barlow.className}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
          <ToastProvider />
          <MainNavigation/>
          <SideNavBar notificationCounts={counts}>
            {children}
          </SideNavBar>
        </ThemeProvider>
      </body>
    </html>
  );
}
