import type { Metadata } from "next";
import localFont from "next/font/local";
import "../globals.css";
import ToastProvider from "../../context/ToastProvider";
import MainNavigation from "../app-components/Navigation";

const barlow = localFont({ src: "../../public/fonts/Barlow-Regular.ttf" });

export const metadata: Metadata = {
  title: "Nomeo Blog 1.0",
  description: "Generated by create next app",
};

export default async function AuthLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={barlow.className}>
        <MainNavigation />
        <ToastProvider />
        {children}
      </body>
    </html>
  );
}
