import type { Metadata } from "next";
import localFont from "next/font/local";
import "../globals.css";
import ToastProvider from "../../context/ToastProvider";
import MainNavigation from "../app-components/Navigation";
import ThemeProvider from "@/context/ThemeProvider";

const barlow = localFont({ src: "../../public/fonts/Barlow-Regular.ttf" });

export const metadata: Metadata = {
  title: "Nomeo Blog 1.0",
  description: "Generated by create next app",
};

export default async function AuthLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="en">
      <body className={barlow.className}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
          <MainNavigation />
          <ToastProvider />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
