import React from "react";
import { getSession } from "../../../libs/actions/data.action";
import EditorClient from "../../../components/editor/EditorClient";
import { Metadata } from "next";
import { redirect } from "next/navigation";
import { fetchCurrentUser } from "@/libs/actions/user.action";


export const metadata: Metadata = {
  title: "Nomeo Blog 1.0 | Editor",
  description: "Generated by create next app",
};

const EditorPage = async () => {
  const currentUser = await fetchCurrentUser();
  const session = await getSession();

  const loggedIn = session && session.user && session.user.email === currentUser.email;

  if (!loggedIn) {
    redirect("sign-in?next=/editor");
  }

  return <EditorClient />;
};

export default EditorPage;
