import React from "react";
import { getCurrentUser, getSession } from "../../../libs/actions/data.action";
import { redirect } from "next/navigation";
import EditorClient from "../../../components/editor/EditorClient";
import { Metadata } from "next";


export const metadata: Metadata = {
  title: "Nomeo Blog 1.0 | Editor",
  description: "Generated by create next app",
};

const EditorPage = async () => {

  const session = await getSession();
  const currentUser = await getCurrentUser();

  if (!session?.user) {
    redirect("/sign-in");
  }

  return <EditorClient />;
};

export default EditorPage;
